package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adicionales generated by hbm2java
 */
@Entity
@Table(name="adicionales"
    ,catalog="restobarpv01"
)
public class Adicionales  implements java.io.Serializable {


     private Integer idAdicionales;
     private VentaComanda ventaComanda;
     private Producto producto;
     private String descripcion;
     private Float precio;

    public Adicionales() {
    }

	
    public Adicionales(VentaComanda ventaComanda, Producto producto) {
        this.ventaComanda = ventaComanda;
        this.producto = producto;
    }
    public Adicionales(VentaComanda ventaComanda, Producto producto, String descripcion, Float precio) {
       this.ventaComanda = ventaComanda;
       this.producto = producto;
       this.descripcion = descripcion;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAdicionales", unique=true, nullable=false)
    public Integer getIdAdicionales() {
        return this.idAdicionales;
    }
    
    public void setIdAdicionales(Integer idAdicionales) {
        this.idAdicionales = idAdicionales;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVenta_Comandacol", nullable=false)
    public VentaComanda getVentaComanda() {
        return this.ventaComanda;
    }
    
    public void setVentaComanda(VentaComanda ventaComanda) {
        this.ventaComanda = ventaComanda;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precio", precision=12, scale=0)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


