package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CancelacionMesa generated by hbm2java
 */
@Entity
@Table(name="cancelacion_mesa"
    ,catalog="restobarpv01"
)
public class CancelacionMesa  implements java.io.Serializable {


     private Integer idCancelacionMesa;
     private MesaVenta mesaVenta;
     private String observaciones;
     private String registro;
     private String autorizacion;

    public CancelacionMesa() {
    }

	
    public CancelacionMesa(MesaVenta mesaVenta) {
        this.mesaVenta = mesaVenta;
    }
    public CancelacionMesa(MesaVenta mesaVenta, String observaciones, String registro, String autorizacion) {
       this.mesaVenta = mesaVenta;
       this.observaciones = observaciones;
       this.registro = registro;
       this.autorizacion = autorizacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCancelacion_Mesa", unique=true, nullable=false)
    public Integer getIdCancelacionMesa() {
        return this.idCancelacionMesa;
    }
    
    public void setIdCancelacionMesa(Integer idCancelacionMesa) {
        this.idCancelacionMesa = idCancelacionMesa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMesa_venta", nullable=false)
    public MesaVenta getMesaVenta() {
        return this.mesaVenta;
    }
    
    public void setMesaVenta(MesaVenta mesaVenta) {
        this.mesaVenta = mesaVenta;
    }
    
    @Column(name="observaciones", length=450)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name="Registro", length=19)
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    
    @Column(name="Autorizacion", length=450)
    public String getAutorizacion() {
        return this.autorizacion;
    }
    
    public void setAutorizacion(String autorizacion) {
        this.autorizacion = autorizacion;
    }




}


