package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CancelacionComanda generated by hbm2java
 */
@Entity
@Table(name="cancelacion_comanda"
    ,catalog="restobarpv01"
)
public class CancelacionComanda  implements java.io.Serializable {


     private Integer idCancelacionComanda;
     private Comanda comanda;
     private String descripcion;
     private String registro;
     private String autorizacion;

    public CancelacionComanda() {
    }

	
    public CancelacionComanda(Comanda comanda) {
        this.comanda = comanda;
    }
    public CancelacionComanda(Comanda comanda, String descripcion, String registro, String autorizacion) {
       this.comanda = comanda;
       this.descripcion = descripcion;
       this.registro = registro;
       this.autorizacion = autorizacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCancelacion_Comanda", unique=true, nullable=false)
    public Integer getIdCancelacionComanda() {
        return this.idCancelacionComanda;
    }
    
    public void setIdCancelacionComanda(Integer idCancelacionComanda) {
        this.idCancelacionComanda = idCancelacionComanda;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idComanda", nullable=false)
    public Comanda getComanda() {
        return this.comanda;
    }
    
    public void setComanda(Comanda comanda) {
        this.comanda = comanda;
    }
    
    @Column(name="descripcion", length=450)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="Registro", length=19)
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    
    @Column(name="Autorizacion", length=450)
    public String getAutorizacion() {
        return this.autorizacion;
    }
    
    public void setAutorizacion(String autorizacion) {
        this.autorizacion = autorizacion;
    }




}


