package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mesas generated by hbm2java
 */
@Entity
@Table(name="mesas"
    ,catalog="restobarpv01"
)
public class Mesas  implements java.io.Serializable {


     private String idMesa;
     private Empleado empleado;
     private Zona zona;
     private String estado;
     private Integer posiscion;
     private String estadodia;
     private String tipo;
     private Set<MesaVenta> mesaVentas = new HashSet<MesaVenta>(0);

    public Mesas() {
    }

	
    public Mesas(String idMesa, Empleado empleado, Zona zona) {
        this.idMesa = idMesa;
        this.empleado = empleado;
        this.zona = zona;
    }
    public Mesas(String idMesa, Empleado empleado, Zona zona, String estado, Integer posiscion, String estadodia, String tipo, Set<MesaVenta> mesaVentas) {
       this.idMesa = idMesa;
       this.empleado = empleado;
       this.zona = zona;
       this.estado = estado;
       this.posiscion = posiscion;
       this.estadodia = estadodia;
       this.tipo = tipo;
       this.mesaVentas = mesaVentas;
    }
   
     @Id 
    
    @Column(name="idMesa", unique=true, nullable=false, length=60)
    public String getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(String idMesa) {
        this.idMesa = idMesa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idzona", nullable=false)
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    
    @Column(name="estado", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="posiscion")
    public Integer getPosiscion() {
        return this.posiscion;
    }
    
    public void setPosiscion(Integer posiscion) {
        this.posiscion = posiscion;
    }
    
    @Column(name="estadodia", length=45)
    public String getEstadodia() {
        return this.estadodia;
    }
    
    public void setEstadodia(String estadodia) {
        this.estadodia = estadodia;
    }
    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="mesas")
    public Set<MesaVenta> getMesaVentas() {
        return this.mesaVentas;
    }
    
    public void setMesaVentas(Set<MesaVenta> mesaVentas) {
        this.mesaVentas = mesaVentas;
    }




}


