package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pagoscorte generated by hbm2java
 */
@Entity
@Table(name="pagoscorte"
    ,catalog="restobarpv01"
)
public class Pagoscorte  implements java.io.Serializable {


     private Integer idPagosCorte;
     private Altadia altadia;
     private Empleado empleado;
     private Float total;
     private String tipopago;
     private Float efectivo;
     private Float tarjetas;

    public Pagoscorte() {
    }

	
    public Pagoscorte(Altadia altadia, Empleado empleado) {
        this.altadia = altadia;
        this.empleado = empleado;
    }
    public Pagoscorte(Altadia altadia, Empleado empleado, Float total, String tipopago, Float efectivo, Float tarjetas) {
       this.altadia = altadia;
       this.empleado = empleado;
       this.total = total;
       this.tipopago = tipopago;
       this.efectivo = efectivo;
       this.tarjetas = tarjetas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idPagosCorte", unique=true, nullable=false)
    public Integer getIdPagosCorte() {
        return this.idPagosCorte;
    }
    
    public void setIdPagosCorte(Integer idPagosCorte) {
        this.idPagosCorte = idPagosCorte;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idaltadia", nullable=false)
    public Altadia getAltadia() {
        return this.altadia;
    }
    
    public void setAltadia(Altadia altadia) {
        this.altadia = altadia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    
    @Column(name="total", precision=12, scale=0)
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    
    @Column(name="tipopago", length=15)
    public String getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(String tipopago) {
        this.tipopago = tipopago;
    }
    
    @Column(name="efectivo", precision=12, scale=0)
    public Float getEfectivo() {
        return this.efectivo;
    }
    
    public void setEfectivo(Float efectivo) {
        this.efectivo = efectivo;
    }
    
    @Column(name="tarjetas", precision=12, scale=0)
    public Float getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Float tarjetas) {
        this.tarjetas = tarjetas;
    }




}


