package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="restobarpv01"
)
public class Producto  implements java.io.Serializable {


     private String idProducto;
     private Categoria categoria;
     private String nombre;
     private Integer tamano;
     private String tipo;
     private String tipoEvento;
     private Float precio;
     private String importacion;
     private String url;
     private String horarioinicial;
     private String horariofinal;
     private String opcion;
     private String medida;
     private Set<Adicionales> adicionaleses = new HashSet<Adicionales>(0);
     private Set<VentaComanda> ventaComandas = new HashSet<VentaComanda>(0);

    public Producto() {
    }

	
    public Producto(String idProducto, Categoria categoria) {
        this.idProducto = idProducto;
        this.categoria = categoria;
    }
    public Producto(String idProducto, Categoria categoria, String nombre, Integer tamano, String tipo, String tipoEvento, Float precio, String importacion, String url, String horarioinicial, String horariofinal, String opcion, String medida, Set<Adicionales> adicionaleses, Set<VentaComanda> ventaComandas) {
       this.idProducto = idProducto;
       this.categoria = categoria;
       this.nombre = nombre;
       this.tamano = tamano;
       this.tipo = tipo;
       this.tipoEvento = tipoEvento;
       this.precio = precio;
       this.importacion = importacion;
       this.url = url;
       this.horarioinicial = horarioinicial;
       this.horariofinal = horariofinal;
       this.opcion = opcion;
       this.medida = medida;
       this.adicionaleses = adicionaleses;
       this.ventaComandas = ventaComandas;
    }
   
     @Id 
    
    @Column(name="idProducto", unique=true, nullable=false, length=30)
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="tamano")
    public Integer getTamano() {
        return this.tamano;
    }
    
    public void setTamano(Integer tamano) {
        this.tamano = tamano;
    }
    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="tipoEvento", length=45)
    public String getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }
    
    @Column(name="precio", precision=12, scale=0)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    
    @Column(name="importacion", length=45)
    public String getImportacion() {
        return this.importacion;
    }
    
    public void setImportacion(String importacion) {
        this.importacion = importacion;
    }
    
    @Column(name="url", length=450)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="horarioinicial", length=45)
    public String getHorarioinicial() {
        return this.horarioinicial;
    }
    
    public void setHorarioinicial(String horarioinicial) {
        this.horarioinicial = horarioinicial;
    }
    
    @Column(name="horariofinal", length=45)
    public String getHorariofinal() {
        return this.horariofinal;
    }
    
    public void setHorariofinal(String horariofinal) {
        this.horariofinal = horariofinal;
    }
    
    @Column(name="opcion", length=45)
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    
    @Column(name="medida", length=45)
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="producto")
    public Set<Adicionales> getAdicionaleses() {
        return this.adicionaleses;
    }
    
    public void setAdicionaleses(Set<Adicionales> adicionaleses) {
        this.adicionaleses = adicionaleses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="producto")
    public Set<VentaComanda> getVentaComandas() {
        return this.ventaComandas;
    }
    
    public void setVentaComandas(Set<VentaComanda> ventaComandas) {
        this.ventaComandas = ventaComandas;
    }




}


