package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VentaComanda generated by hbm2java
 */
@Entity
@Table(name="venta_comanda"
    ,catalog="restobarpv01"
)
public class VentaComanda  implements java.io.Serializable {


     private Integer idVentaComandacol;
     private Comanda comanda;
     private Descuento descuento;
     private Barra barra;
     private Producto producto;
     private String observaciones;
     private String registro;
     private String estado;
     private String actorizacion;
     private Float costo;
     private Float costoOriginal;
     private Set<Cancelacionproducto> cancelacionproductos = new HashSet<Cancelacionproducto>(0);
     private Set<Transladoproducto> transladoproductos = new HashSet<Transladoproducto>(0);
     private Set<Adicionales> adicionaleses = new HashSet<Adicionales>(0);

    public VentaComanda() {
    }

	
    public VentaComanda(Comanda comanda, Barra barra, Producto producto) {
        this.comanda = comanda;
        this.barra = barra;
        this.producto = producto;
    }
    public VentaComanda(Comanda comanda, Descuento descuento, Barra barra, Producto producto, String observaciones, String registro, String estado, String actorizacion, Float costo, Float costoOriginal, Set<Cancelacionproducto> cancelacionproductos, Set<Transladoproducto> transladoproductos, Set<Adicionales> adicionaleses) {
       this.comanda = comanda;
       this.descuento = descuento;
       this.barra = barra;
       this.producto = producto;
       this.observaciones = observaciones;
       this.registro = registro;
       this.estado = estado;
       this.actorizacion = actorizacion;
       this.costo = costo;
       this.costoOriginal = costoOriginal;
       this.cancelacionproductos = cancelacionproductos;
       this.transladoproductos = transladoproductos;
       this.adicionaleses = adicionaleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idVenta_Comandacol", unique=true, nullable=false)
    public Integer getIdVentaComandacol() {
        return this.idVentaComandacol;
    }
    
    public void setIdVentaComandacol(Integer idVentaComandacol) {
        this.idVentaComandacol = idVentaComandacol;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idComanda", nullable=false)
    public Comanda getComanda() {
        return this.comanda;
    }
    
    public void setComanda(Comanda comanda) {
        this.comanda = comanda;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDescuento")
    public Descuento getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Descuento descuento) {
        this.descuento = descuento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBarra", nullable=false)
    public Barra getBarra() {
        return this.barra;
    }
    
    public void setBarra(Barra barra) {
        this.barra = barra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    
    @Column(name="Observaciones", length=450)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
   
    @Column(name="registro", length=19)
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="Actorizacion", length=450)
    public String getActorizacion() {
        return this.actorizacion;
    }
    
    public void setActorizacion(String actorizacion) {
        this.actorizacion = actorizacion;
    }
    
    @Column(name="costo", precision=12, scale=0)
    public Float getCosto() {
        return this.costo;
    }
    
    public void setCosto(Float costo) {
        this.costo = costo;
    }
    
    @Column(name="costoOriginal", precision=12, scale=0)
    public Float getCostoOriginal() {
        return this.costoOriginal;
    }
    
    public void setCostoOriginal(Float costoOriginal) {
        this.costoOriginal = costoOriginal;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ventaComanda")
    public Set<Cancelacionproducto> getCancelacionproductos() {
        return this.cancelacionproductos;
    }
    
    public void setCancelacionproductos(Set<Cancelacionproducto> cancelacionproductos) {
        this.cancelacionproductos = cancelacionproductos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ventaComanda")
    public Set<Transladoproducto> getTransladoproductos() {
        return this.transladoproductos;
    }
    
    public void setTransladoproductos(Set<Transladoproducto> transladoproductos) {
        this.transladoproductos = transladoproductos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ventaComanda")
    public Set<Adicionales> getAdicionaleses() {
        return this.adicionaleses;
    }
    
    public void setAdicionaleses(Set<Adicionales> adicionaleses) {
        this.adicionaleses = adicionaleses;
    }




}


