package com.mapping;
// Generated 11/04/2015 07:19:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,catalog="restobarpv01"
)
public class Zona  implements java.io.Serializable {


     private String idzona;
     private String piso;
     private String ubicaion;
     private String descripcion;
     private Set<MesaVenta> mesaVentas = new HashSet<MesaVenta>(0);
     private Set<Mesas> mesases = new HashSet<Mesas>(0);

    public Zona() {
    }

	
    public Zona(String idzona) {
        this.idzona = idzona;
    }
    public Zona(String idzona, String piso, String ubicaion, String descripcion, Set<MesaVenta> mesaVentas, Set<Mesas> mesases) {
       this.idzona = idzona;
       this.piso = piso;
       this.ubicaion = ubicaion;
       this.descripcion = descripcion;
       this.mesaVentas = mesaVentas;
       this.mesases = mesases;
    }
   
     @Id 
    
    @Column(name="idzona", unique=true, nullable=false, length=30)
    public String getIdzona() {
        return this.idzona;
    }
    
    public void setIdzona(String idzona) {
        this.idzona = idzona;
    }
    
    @Column(name="Piso", length=45)
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    
    @Column(name="ubicaion", length=45)
    public String getUbicaion() {
        return this.ubicaion;
    }
    
    public void setUbicaion(String ubicaion) {
        this.ubicaion = ubicaion;
    }
    
    @Column(name="descripcion", length=145)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="zona")
    public Set<MesaVenta> getMesaVentas() {
        return this.mesaVentas;
    }
    
    public void setMesaVentas(Set<MesaVenta> mesaVentas) {
        this.mesaVentas = mesaVentas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="zona")
    public Set<Mesas> getMesases() {
        return this.mesases;
    }
    
    public void setMesases(Set<Mesas> mesases) {
        this.mesases = mesases;
    }




}


